### PR TITLE
Added home page

### PR DESCRIPTION
**Pull request by Ashish13singh**
fixed issue #1

### CODE REVIEW

**Comment by patelyash5208** [comment]
please provide screenshot @Ashish13singh

**Comment by patelyash5208** [comment]
please don't repeat code only change and commit screeenshot @Ashish13singh

**Comment by Ashish13singh** [comment]
> please provide screenshot @Ashish13singh

Screenshot (20)

**Comment by patelyash5208** [comment]
Please add some design

**Comment by patelyash5208** [comment]
In home page you have to add all details about T20 world cup with style and meaningfully details. @Ashish13singh

**Comment by Ashish13singh** [comment]
@patelyash5208, can you add a hactoberfest-accepted label on this PR?

**Pull request merged**
