### PR TITLE
fix: Create a new file for venues and add to navbar #2

### PR DESCRIPTION
**Pull request by Ashish13singh**
Create a new file for venues and add to navbar #2

### CODE REVIEW

**Comment by Ashish13singh** [comment]
image

**Comment by patelyash5208** [comment]
You can make like this

**Comment by Ashish13singh** [comment]
@patelyash5208 do you want me to change or update anything?

**Comment by patelyash5208** [comment]
Change the file like I have send you. @Ashish13singh

**Comment by Ashish13singh** [comment]
@patelyash5208, can you resend the file? I am not able to find it.

**Comment by Ashish13singh** [comment]
@patelyash5208, I am still not able to find that file. Can you resend it to my Gmail account ashish212.as877@gmailcom

**Comment by patelyash5208** [comment]
@Ashish13s please star the repo.
and kindly inform about that counter start on your hacktoberfest website.

**Comment by Ashish13singh** [comment]
The counter started, as you can see in the below picture.

[image: image.png]

Can you please add more issues so I can work on them for hactoberfest? And
yes, I have started this repository.

**Comment by Ashish13singh** [comment]
The counter has started.
image

**Comment by patelyash5208** [comment]
Sure, here it is.

**Pull request merged**
